baseURL = "tudiosainterior.com"
disableLanguages = ["fr"]
disqusShortname = ""
googleAnalytics = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
timeZone = "UTC"
title = "Tu diosa interior"
[languages.de]
contentDir = "content/german"
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). Alle Rechte vorbehalten."
languageCode = "de-DE"
languageName = "Deutsch"
weight = 3
[[languages.de.menu.main]]
hasChildren = true
name = "Mehr"
weight = 5
[languages.en]
contentDir = "content/english"
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). All Rights Reserved."
languageCode = "en-US"
languageName = "English"
weight = 1
[[languages.en.menu.main]]
hasChildren = true
name = "More"
weight = 5
[languages.fr]
contentDir = "content/french"
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). Tous droits réservés."
languageCode = "fr-FR"
languageName = "Français"
weight = 2
[[languages.fr.menu.main]]
hasChildren = true
name = "Plus"
weight = 5
[languages.it]
contentDir = "content/italian"
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). Tutti i diritti riservati."
languageCode = "it-IT"
languageName = "Italiano"
weight = 2
[[languages.it.menu.main]]
hasChildren = true
name = "Più"
weight = 5
[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 2
[module.hugoVersion]
extended = true
min = "0.87.0"
[outputs]
home = ["HTML"]
[params]
author = "Amy Cohen"
description = "Círculo de mujeres Tu Diosa Interior"
image = "images/logo.png"
logo = "images/logo.png"
logo_width = "150px"
[params.contact]
address_descriptors = false
email = "conectacontudiosainterior@gmail.com"
location = "Bali Indonesia"
phone = "+34 697810608"
[params.contact.form]
action = "#"
enable = false
success_image = "images/paper-plane.svg"
use_netlify = false
[params.cookies]
enable = true
expire_days = 2
[params.counter]
enable = true
username = ""
[params.gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[[params.plugins.css]]
attributes = "media='screen'"
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/ionicons/css/ionicons.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.css"
[[params.plugins.css]]
attributes = ""
link = "plugins/slick/slick.css"
[[params.plugins.js]]
attributes = ""
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/magnific-popup/magnific-popup.min.js"
[[params.plugins.js]]
attributes = ""
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
attributes = "defer"
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = ""
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-googleplus-outline"
link = "#"
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "#"
[[params.social]]
icon = "ion-social-dribbble-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
